#!/bin/bash
set -e

PG_HOME="/var/lib/postgresql"
PG_DATA="${PG_HOME}/9.4"

if [ -n "${DB_USER}" ]; then
  if [ -z "${DB_PASS}" ]; then
    echo ""
    echo "WARNING: "
    echo "  Please specify a password for \"${DB_USER}\". Skipping user creation..."
    echo ""
    DB_USER=
  else
    echo "Creating user \"${DB_USER}\"..."
    echo "CREATE ROLE ${DB_USER} with LOGIN CREATEDB PASSWORD '${DB_PASS}';" |
      sudo -u postgres /usr/lib/postgresql-9.4/bin/postgres --single -D ${PG_DATA} -c config_file=/etc/postgresql-9.4/postgresql.conf >/dev/null
  fi
fi

if [ -n "${DB_NAME}" ]; then
    echo "Creating database \"${DB_NAME}\"..."
    echo "CREATE DATABASE ${DB_NAME};" | \
      sudo -u postgres /usr/lib/postgresql-9.4/bin/postgres --single -D ${PG_DATA} -c config_file=/etc/postgresql-9.4/postgresql.conf >/dev/null

    if [ -n "${DB_USER}" ]; then
      echo "Granting access to database \"${DB_NAME}\" for user \"${DB_USER}\"..."
      echo "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} to ${DB_USER};" |
        sudo -u postgres /usr/lib/postgresql-9.4/bin/postgres --single -D ${PG_DATA} -c config_file=/etc/postgresql-9.4/postgresql.conf >/dev/null
    fi
fi

echo "Starting the server..."
exec sudo -u postgres /usr/lib/postgresql-9.4/bin/postgres -D ${PG_DATA} -c config_file=/etc/postgresql-9.4/postgresql.conf
